services:
  web:
    build:
      target: development
    image: openskope/skopeui:dev
    volumes:
      - ./app:/code
      - /code/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    command: npm run dev
