name: Build/Test Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate citation files for build constants
        run: make citations
      - name: Build nuxt site for production deployment
        run: make buildprod
